### ISSUE TITLE
Add complete example of code

### ISSUE THREAD

**Issue by Just-m** [incognitochain/sdk#1]
I think it would help many to have one complete example of code.
For example: How to query accountHistory

I tried it this way.
```
const SDK = require('incognito-sdk');
const sdkConfig = require('./config.js');

SDK.start(sdkConfig, (error, sdk) => {
	sdk.account.getAccountHistory(sdkConfig.DEFAULT_ACCOUNT_PRIVATE_KEY);
});
```
The output shows all my (derived) keys correctly,
but then I get this error.
Error: Validating "account" failed: Invalid account wallet. 
Should this work, or am I missing something?

**Comment by keresh93v** [comment]
We're sorry about it, we will update a full document soon. For your case:
`SDK.start(config, (error, sdk) => {
  if (error) {
    console.error('Load SDK failed');
    return;
  }
  
  console.debug('SDK is ready! See all supported methods here', sdk);

  // Get default account with DEFAULT_ACCOUNT_PRIVATE_KEY defined in env/[mode].env.js
  const defaultAccount = sdk.account.getDefaultAccount();
  console.debug('DEFAULT ACCOUNT', defaultAccount);

 // Load accouny history (use account object instead, not account's private key)
 sdk.account.getAccountHistory(defaultAccount);
  `
